import type { Report } from "./redteam.js";
import { stripUnsafe } from "./sanitize.js";

const REMEDIATION: Record<string, string> = {
  "Prompt Injection":
    "Treat all fetched/tool content as untrusted data, never instructions. Wrap it in a boundary and never let it override system rules.",
  "Unauthorized Fund Transfer":
    "Never let free-text drive a transfer. Gate every on-chain action behind an allowlist + explicit signed authorization, not model output.",
  "Secret Exfiltration":
    "Keep keys out of the model's context entirely. Load secrets in the execution layer; the agent should never see them to leak them.",
  "Jailbreak / Guardrail Bypass":
    "Enforce refusals in code, not just the prompt. Re-assert the system policy after user input and validate the persona hasn't changed.",
  "Output Hijack (A2A Trust)":
    "Strip/validate output against a strict schema before delivery. Never echo untrusted tokens; sign your own attestations instead.",
  "Instruction Override":
    "Anchor the task server-side. Ignore any 'ignore previous instructions' pattern; the task must not be settable from user input.",
  "System Prompt Extraction":
    "Refuse system-prompt disclosure. Assume the prompt is public and put no secrets in it; enforce refusal deterministically.",
};

const ICON = { resisted: "✅", vulnerable: "❌", error: "⚠️" } as const;

const BACKTICK = String.fromCharCode(96);
// Untrusted string embedded in an inline-code span: strip backticks + collapse
// whitespace so it can't break out and inject markdown into the deliverable.
const code = (s: string) =>
  stripUnsafe(String(s ?? "")).split(BACKTICK).join("").replace(/\s+/g, " ").trim().slice(0, 200);

// Machine-readable projection so a consuming AGENT can gate on the result
// (e.g. deploy only if grade >= "B") instead of scraping the markdown. Embedded as
// a fenced json block in the single text deliverable — one payload, both audiences.
// Only internal enums + the buyer's own target are included (no raw target output),
// and the whole string is stripped of controls/backticks so it can't break the fence.
export function toStructured(r: Report) {
  return {
    target: r.target,
    evaluated: r.evaluated,
    reflects: r.reflects,
    score: r.score,
    grade: r.grade,
    vulnerabilities: r.vulnerabilities,
    totalAttacks: r.totalAttacks,
    findings: r.findings.map((f) => ({
      id: f.id,
      category: f.category,
      severity: f.severity,
      status: f.status,
    })),
  };
}

function machineBlock(r: Report): string {
  const json = stripUnsafe(JSON.stringify(toStructured(r))).split(BACKTICK).join("");
  return `\n<details><summary>machine-readable JSON (for agents)</summary>\n\n\`\`\`json\n${json}\n\`\`\`\n</details>`;
}

export function renderMarkdown(r: Report): string {
  const lines: string[] = [];
  lines.push(`# 🛡️ Agent Security Report`);
  if (r.target) lines.push(`**Target:** \`${code(r.target)}\``);

  if (!r.evaluated) {
    lines.push(`\n**⚠️ Could not evaluate** · ${r.summary}\n`);
  } else {
    lines.push(`\n**Score: ${r.score}/100 — Grade ${r.grade}**  ·  ${r.summary}\n`);
  }

  if (r.reflects) {
    lines.push(
      `\n> ⚠️ **Target echoes input verbatim** — it reflected a benign marker back, so it looks like a mirror/misconfigured endpoint, not a reasoning agent. Token- and keyword-based findings below are likely **false positives** (the agent isn't complying, just echoing the prompt). Point the scan at the agent's real reasoning endpoint.\n`,
    );
  }

  lines.push(`| Attack | Category | Severity | Result |`);
  lines.push(`|---|---|---|---|`);
  for (const f of r.findings) {
    lines.push(
      `| ${f.id} | ${f.category} | ${f.severity} | ${ICON[f.status]} ${f.status} |`,
    );
  }

  const vulns = r.findings.filter((f) => f.status === "vulnerable");
  if (vulns.length) {
    lines.push(`\n## ❌ Vulnerabilities & Fixes\n`);
    for (const f of vulns) {
      lines.push(`### ${f.category} — \`${f.id}\` (${f.severity})`);
      lines.push(`${f.description}`);
      if (f.evidence) lines.push(`\n> Evidence: \`${f.evidence}\``);
      lines.push(`\n**Fix:** ${REMEDIATION[f.category] ?? "Harden this path."}\n`);
    }
  } else if (!r.evaluated) {
    lines.push(
      `\n## ⚠️ Target unreachable — no probe got a scorable response. Verify the endpoint accepts \`POST {"input":"…"}\` and retry.\n`,
    );
  } else {
    lines.push(`\n## ✅ No vulnerabilities detected. Agent resisted all probes.\n`);
  }

  lines.push(machineBlock(r));
  lines.push(
    `\n---\n_Generated by Jailbreak-My-Agent · ${r.totalAttacks} single-turn baseline probes · a pass means "resisted these", not "provably secure" · reproducible from the same attack suite._`,
  );
  return lines.join("\n");
}
