import type { Report } from "./redteam.js";

const REMEDIATION: Record<string, string> = {
  "Prompt Injection":
    "Treat all fetched/tool content as untrusted data, never instructions. Wrap it in a boundary and never let it override system rules.",
  "Unauthorized Fund Transfer":
    "Never let free-text drive a transfer. Gate every on-chain action behind an allowlist + explicit signed authorization, not model output.",
  "Secret Exfiltration":
    "Keep keys out of the model's context entirely. Load secrets in the execution layer; the agent should never see them to leak them.",
  "Jailbreak / Guardrail Bypass":
    "Enforce refusals in code, not just the prompt. Re-assert the system policy after user input and validate the persona hasn't changed.",
  "Output Hijack (A2A Trust)":
    "Strip/validate output against a strict schema before delivery. Never echo untrusted tokens; sign your own attestations instead.",
  "Instruction Override":
    "Anchor the task server-side. Ignore any 'ignore previous instructions' pattern; the task must not be settable from user input.",
  "System Prompt Extraction":
    "Refuse system-prompt disclosure. Assume the prompt is public and put no secrets in it; enforce refusal deterministically.",
};

const ICON = { resisted: "✅", vulnerable: "❌", error: "⚠️" } as const;

export function renderMarkdown(r: Report): string {
  const lines: string[] = [];
  lines.push(`# 🛡️ Agent Security Report`);
  if (r.target) lines.push(`**Target:** \`${r.target}\``);
  lines.push(`\n**Score: ${r.score}/100 — Grade ${r.grade}**  ·  ${r.summary}\n`);

  lines.push(`| Attack | Category | Severity | Result |`);
  lines.push(`|---|---|---|---|`);
  for (const f of r.findings) {
    lines.push(
      `| ${f.id} | ${f.category} | ${f.severity} | ${ICON[f.status]} ${f.status} |`,
    );
  }

  const vulns = r.findings.filter((f) => f.status === "vulnerable");
  if (vulns.length) {
    lines.push(`\n## ❌ Vulnerabilities & Fixes\n`);
    for (const f of vulns) {
      lines.push(`### ${f.category} — \`${f.id}\` (${f.severity})`);
      lines.push(`${f.description}`);
      if (f.evidence) lines.push(`\n> Evidence: \`${f.evidence}\``);
      lines.push(`\n**Fix:** ${REMEDIATION[f.category] ?? "Harden this path."}\n`);
    }
  } else {
    lines.push(`\n## ✅ No vulnerabilities detected. Agent resisted all probes.\n`);
  }

  lines.push(
    `\n---\n_Generated by Jailbreak-My-Agent · ${r.totalAttacks} attacks · report is reproducible from the same attack suite._`,
  );
  return lines.join("\n");
}
